"""Configuration schema using Pydantic for validation."""

from pathlib import Path
from typing import Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


# Collision primitive strategies generated by the converter.
#   mesh          - decimated copy of the visual mesh (legacy default)
#   trunk_cylinder- thin upright cylinder fitted to the base footprint (trees/bushes)
#   convex_hull   - convex hull of all geometry (rocks/boulders)
#   box / sphere  - axis-aligned bounds primitive
COLLISION_STRATEGIES = {"mesh", "trunk_cylinder", "convex_hull", "box", "sphere"}


class CategoryConfig(BaseModel):
    """Per-category overrides for asset conversion.

    Any field left as ``None`` falls back to ``BlenderConfig``'s global
    ``visual_decimation`` / ``collision_decimation``. An empty
    ``BlenderConfig.categories`` therefore reproduces the legacy behaviour
    exactly (blanket decimation + decimated-mesh collision).
    """

    visual_decimation: Optional[float] = Field(
        default=None, ge=0.01, le=1.0,
        description="Visual decimation ratio for this category (None -> global). 1.0 = no decimation."
    )
    collision_decimation: Optional[float] = Field(
        default=None, ge=0.001, le=0.5,
        description="Collision decimation ratio when collision_strategy='mesh' (None -> global)."
    )
    collision_strategy: str = Field(
        default="mesh",
        description="Collision shape: mesh | trunk_cylinder | convex_hull | box | sphere."
    )
    skip_foliage_decimation: bool = Field(
        default=False,
        description="Skip the Decimate modifier on objects that have any alpha (foliage) material slot."
    )
    passable: Optional[bool] = Field(
        default=None,
        description="Robots drive through this category (collide_without_contact + "
                    "zero collide_bitmask) while lidar still hits it. None -> "
                    "category default (grass/bush passable, everything else solid)."
    )
    laser_retro: Optional[float] = Field(
        default=None,
        description="laser_retro written on both the visual and the collision "
                    "(gz gpu_lidar reads visuals; CPU ray sensors read "
                    "collisions) so simulated lidar intensity identifies the "
                    "category (CropCraft-style semantic labels). None -> "
                    "category default (tree=1 bush=2 rock=3 grass=4 sand=5; "
                    "ground stays 0)."
    )

    @field_validator("collision_strategy")
    @classmethod
    def validate_strategy(cls, v):
        if v not in COLLISION_STRATEGIES:
            raise ValueError(
                f"collision_strategy must be one of {sorted(COLLISION_STRATEGIES)}, got {v!r}"
            )
        return v


class BlenderConfig(BaseModel):
    """Blender configuration for asset conversion."""

    path: Optional[Path] = Field(
        default=None, description="Path to Blender executable (auto-detected if None)"
    )
    visual_decimation: float = Field(
        default=0.1, ge=0.01, le=1.0, description="Decimation ratio for visual mesh"
    )
    collision_decimation: float = Field(
        default=0.01, ge=0.001, le=0.5, description="Decimation ratio for collision mesh"
    )
    categories: Dict[str, CategoryConfig] = Field(
        default_factory=dict,
        description="Per-category conversion overrides keyed by category name (tree, rock, bush, ...)."
    )

    def resolve_category(self, category: str) -> "ResolvedCategory":
        """Resolve effective conversion parameters for a category.

        Falls back to the global decimation ratios for any unset per-category
        field. With no entry for ``category`` this yields the legacy defaults.
        """
        cc = self.categories.get(category, CategoryConfig())
        return ResolvedCategory(
            visual_decimation=(
                cc.visual_decimation if cc.visual_decimation is not None
                else self.visual_decimation
            ),
            collision_decimation=(
                cc.collision_decimation if cc.collision_decimation is not None
                else self.collision_decimation
            ),
            collision_strategy=cc.collision_strategy,
            skip_foliage_decimation=cc.skip_foliage_decimation,
            passable=(cc.passable if cc.passable is not None
                      else PASSABLE_DEFAULTS.get(category, False)),
            laser_retro=(cc.laser_retro if cc.laser_retro is not None
                         else LASER_RETRO_DEFAULTS.get(category, 0.0)),
        )

    @field_validator("path", mode="before")
    @classmethod
    def expand_path(cls, v):
        if v is None:
            return v
        return Path(v).expanduser().resolve()


# Per-category defaults for the CropCraft-inspired SDF semantics: understory is
# passable (robots drive through it, lidar still returns), and each category
# carries a distinct laser_retro so lidar intensity doubles as a class label.
PASSABLE_DEFAULTS = {"grass": True, "bush": True}
LASER_RETRO_DEFAULTS = {"tree": 1.0, "bush": 2.0, "rock": 3.0, "grass": 4.0,
                        "sand": 5.0}


class ResolvedCategory(BaseModel):
    """Effective per-asset conversion parameters (no None fallbacks left)."""

    visual_decimation: float
    collision_decimation: float
    collision_strategy: str
    skip_foliage_decimation: bool
    passable: bool = False
    laser_retro: float = 0.0


class GroundLayerSpec(BaseModel):
    """One overlay layer in a patchy ground composite (patch or trail)."""

    material: str = Field(description="Material key (texture-pack id, e.g. ambientCG 'Gravel023').")
    kind: str = Field(default="patch", description="'patch' (organic blobs) or 'trail' (path).")
    tile_m: float = Field(default=3.0, gt=0, description="Tiling period of this material, metres.")
    # patch params
    coverage: float = Field(default=0.08, ge=0.0, le=1.0, description="Patch area fraction.")
    scale_m: float = Field(default=15.0, gt=0, description="Patch feature size, metres.")
    # trail params
    width_m: float = Field(default=2.5, gt=0, description="Trail width, metres.")
    count: int = Field(default=1, ge=1, le=20, description="Number of trails (patch count is implicit via noise).")
    waypoints: Optional[list] = Field(
        default=None, description="Explicit trail waypoints as [[u,v],...] in 0..1; else seeded random walk."
    )

    @field_validator("kind")
    @classmethod
    def _valid_kind(cls, v):
        if v not in ("patch", "trail"):
            raise ValueError("kind must be 'patch' or 'trail'")
        return v


class GroundConfig(BaseModel):
    """Procedural ground material configuration (uniform or seeded patchy)."""

    mode: str = Field(default="uniform", description="'uniform' (tiled single texture), 'patchy' (baked composite), or 'wild' (seeded unrealistic domain-randomization patterns; no texture packs needed).")
    biome: str = Field(default="grassland", description="Preset: grassland | desert | gravel | snow.")
    seed: int = Field(default=0, description="RNG seed; same seed -> same ground (reproducible scenarios).")
    resolution: int = Field(default=4096, ge=512, le=16384, description="Patchy bake resolution (px).")
    randomize: bool = Field(default=True, description="Jitter patch coverage/size by seed.")
    base_material: Optional[str] = Field(default=None, description="Override the biome's base material key.")
    uniform_tile: float = Field(default=8.0, gt=0, description="Uniform-mode UV tiling (repeats across terrain).")
    tile_warp: float = Field(default=1.3, ge=0.0, description="Patchy-mode domain warp of the tiling grid, in tile units (wobble period ~6x the base tile, ~40 m). Bends the periodic grid into a non-periodic one so the tiling-autocorrelation peak collapses (VIO de-aliasing). 0 = off (sharp grid).")
    texture_root: Optional[Path] = Field(
        default=None, description="Directory holding CC0 ground texture packs (default: Blender-Assets/soil)."
    )
    layers: Optional[List[GroundLayerSpec]] = Field(
        default=None, description="Override the biome's overlay layers."
    )
    water_level: Optional[float] = Field(
        default=None, description="If set, add a flat water plane at this terrain-Z height (metres)."
    )
    hsv_jitter: float = Field(
        default=0.0, ge=0.0, le=1.0,
        description="Seeded hue/saturation/value shift of the baked ground albedo "
                    "(0 = off, 1 = strong). Domain randomization for perception "
                    "training: same seed -> same shift."
    )

    @field_validator("mode")
    @classmethod
    def _valid_mode(cls, v):
        if v not in ("uniform", "patchy", "wild"):
            raise ValueError("mode must be 'uniform', 'patchy' or 'wild'")
        return v

    @field_validator("texture_root", mode="before")
    @classmethod
    def _expand_root(cls, v):
        return None if v is None else Path(v).expanduser().resolve()


# Procedural terrain presets. Keep in sync with core/terraingen.py::PRESETS.
PRESET_NAMES = ("hilly", "flat", "mountainous", "valley", "lakeland")


class TerrainGenConfig(BaseModel):
    """Seeded procedural terrain (DEM) synthesis configuration.

    A preset supplies feature defaults; any field set here overrides the preset.
    Same ``seed`` + params -> same landform (reproducible VIO/lidar scenarios).
    Distances are in metres.
    """

    seed: int = Field(default=0, description="RNG seed; same seed -> same landform.")
    preset: str = Field(default="hilly", description="hilly | flat | mountainous | valley | lakeland.")
    resolution: int = Field(default=192, ge=32, le=512, description="DEM pixels per side (== mesh density).")
    pixel_m: float = Field(default=2.5, gt=0, description="Ground sample distance (metres/pixel).")
    # feature overrides (None -> preset default)
    amplitude_m: Optional[float] = Field(default=None, ge=0.0, description="fBm base relief (metres).")
    roughness: Optional[float] = Field(default=None, gt=0.0, le=1.0, description="Per-octave amplitude falloff.")
    octaves: Optional[int] = Field(default=None, ge=1, le=10, description="fBm octave count.")
    feature_m: Optional[float] = Field(default=None, gt=0.0, description="Largest hill feature size (metres).")
    ridged: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Ridged-noise blend (sharper valleys/ridges).")
    detail: Optional[float] = Field(default=None, ge=0.0, le=1.0, description="Fine-octave weight (1=full surface detail, 0=smooth slopes); keeps the macro hill/mountain pattern.")
    slope_m: Optional[float] = Field(default=None, ge=0.0, description="Planar tilt added across the map (metres).")
    valley: Optional[bool] = Field(default=None, description="Carve a central trough.")
    n_peaks: Optional[int] = Field(default=None, ge=0, le=50, description="Number of Gaussian peaks/mounts.")
    n_basins: Optional[int] = Field(default=None, ge=0, le=20, description="Number of basins (mini-lakes).")
    n_creeks: Optional[int] = Field(default=None, ge=0, le=10, description="Number of carved creeks.")
    creek_depth_m: Optional[float] = Field(default=None, gt=0.0, description="Creek channel depth (metres).")
    creek_width_m: Optional[float] = Field(default=None, gt=0.0, description="Creek flat-bed width (metres).")
    edge_taper: Optional[float] = Field(default=None, ge=0.0, le=0.5, description="Border relief taper fraction (None -> preset/0.12; lakeland uses less to avoid a flooded perimeter).")
    smooth_sigma: float = Field(default=0.8, ge=0.0, le=5.0, description="Final anti-facet Gaussian smooth (pixels).")
    max_mean_slope_deg: float = Field(
        default=0.0, ge=0.0, le=60.0,
        description="Ground-robot slope cap: if the synthesized DEM's mean surface "
                    "slope exceeds this, the whole relief is rescaled to meet it "
                    "exactly (slope is linear in height scale). 0 = off (aerial/"
                    "scenery use). `scenario` defaults this to 20.")
    scale_factor: float = Field(default=1.0, gt=0.0, description="Mirror of TerrainConfig.scale_factor (for lake XY report).")

    @field_validator("preset")
    @classmethod
    def _valid_preset(cls, v):
        if v not in PRESET_NAMES:
            raise ValueError(f"preset must be one of {PRESET_NAMES}, got {v!r}")
        return v


class TerrainConfig(BaseModel):
    """Terrain generation configuration."""

    scale_factor: float = Field(default=1.0, ge=0.1, le=100.0, description="Scale factor")
    smooth_sigma: float = Field(default=1.0, ge=0.0, le=10.0, description="Gaussian smoothing")
    enhance: bool = Field(default=False, description="Enable DEM enhancement")
    enhance_scale: float = Field(default=6.0, ge=1.0, le=20.0, description="Enhancement scale")
    texture_blend: Optional[Path] = Field(
        default=None, description="Path to Blender file for terrain texture extraction"
    )
    material_name: str = Field(
        default="Terrain/Ground", description="Name for the generated material"
    )
    ground: Optional[GroundConfig] = Field(
        default=None, description="Procedural ground material (uniform/patchy); None = legacy/extracted texture."
    )

    @field_validator("texture_blend", mode="before")
    @classmethod
    def expand_texture_path(cls, v):
        if v is None:
            return v
        return Path(v).expanduser().resolve()


class DensityConfig(BaseModel):
    """Forest population density configuration."""

    tree: int = Field(default=50, ge=0, le=1000, description="Number of trees")
    bush: int = Field(default=10, ge=0, le=500, description="Number of bushes")
    rock: int = Field(default=5, ge=0, le=200, description="Number of rocks")
    grass: int = Field(default=50, ge=0, le=2000, description="Number of grass patches")
    sand: int = Field(default=5, ge=0, le=100, description="Number of sand patches")


class PathsConfig(BaseModel):
    """Project paths configuration."""

    base_path: Optional[Path] = Field(
        default=None, description="Project base path (auto-detected if None)"
    )
    models_path: Optional[Path] = Field(default=None, description="Models directory")
    worlds_path: Optional[Path] = Field(default=None, description="Worlds directory")

    @field_validator("base_path", "models_path", "worlds_path", mode="before")
    @classmethod
    def expand_path(cls, v):
        if v is None:
            return v
        return Path(v).expanduser().resolve()


class WildSeedConfig(BaseModel):
    """Main configuration schema for WildSeed."""

    blender: BlenderConfig = Field(default_factory=BlenderConfig)
    terrain: TerrainConfig = Field(default_factory=TerrainConfig)
    density: DensityConfig = Field(default_factory=DensityConfig)
    paths: PathsConfig = Field(default_factory=PathsConfig)

    model_config = {"extra": "ignore"}
